---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: trusted-api
  labels:
    app.kubernetes.io/name: trusted-api
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: trusted
spec: {}
