---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: console
  labels:
    app.kubernetes.io/name: console
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: trusted
spec: {}
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: trunk
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: 'ghcr.io/ctron/trunk:latest'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: ubi9-minimal
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: 'registry.access.redhat.com/ubi9/ubi-minimal:latest'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
