kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: guac
  labels:
    app.kubernetes.io/name: guac
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: trusted
spec:
  triggers:
    - type: ImageChange
    - type: ConfigChange
  source:
    git:
      uri: https://github.com/xkcd-2347/guac
      ref: trust-api
  strategy:
    dockerStrategy:
      dockerfilePath: dockerfiles/Dockerfile.guac-ubi
  output:
    to:
      kind: ImageStreamTag
      name: guac:latest
