apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    image.openshift.io/triggers: |
      [
        {
          "from": {
            "kind":"ImageStreamTag",
            "name":"guac:latest"
          },
          "fieldPath":"spec.template.spec.containers[?(@.name==\"guac\")].image"
        }
      ]
  labels:
    app.kubernetes.io/name: guac
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: trusted
  name: guac
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: guac
      app.kubernetes.io/component: backend
      app.kubernetes.io/part-of: trusted
  template:
    metadata:
      labels:
        app.kubernetes.io/name: guac
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: trusted
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - image: guac:latest
          imagePullPolicy: Always
          name: guac
          command:
            - sh
            - -c
            - /opt/guac/guacgql --gql-debug
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 20
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "sleep 5 && curl https://codeload.github.com/xkcd-2347/trust-api/tar.gz/main | tar -xz -C /data --strip=2 trust-api-main/data/files && /opt/guac/guacone collect files /data"]

