apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: guac
  name: guac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guac
  template:
    metadata:
      labels:
        app: guac
    spec:
      containers:
        - image: ghcr.io/xkcd-2347/guac-data:latest
          imagePullPolicy: Always
          args: ["gql-server", "--gql-debug"]
          name: guac
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /openapi.json
              port: 8080
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /openapi.json
              port: 8080
            initialDelaySeconds: 10
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "sleep 5 && /guacone files /data"]
