apiVersion: v1
kind: Service
metadata:
  labels:
    app: guac
  name: guac
spec:
  ports:
  - name: endpoint
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: guac
  type: ClusterIP
